# Generated by Django 5.2.5 on 2025-10-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("programming", "Программирование"),
                    ("django", "Django"),
                    ("python", "Python"),
                    ("web", "Веб-разработка"),
                    ("other", "Другое"),
                ],
                default="other",
                max_length=20,
                verbose_name="Категория",
            ),
        ),
    ]
