# Generated by Django 5.2.5 on 2025-10-09 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="post_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="main.post",
            ),
            preserve_default=False,
        ),
    ]
